### ISSUE TITLE
Chisel can't be opened (mb has to do something with #39)

### ISSUE THREAD

**Issue by TeslaP09** [sleepingdragoninn/inventory-tabs#48]
Well hi, I'm back again:> The Tech Reborn issue (#39) has been fixed, but now I am encountering the same issue when trying to right click with the chisel from Chisel Reborn (https://github.com/matthewperiut/Chisel-Reborn). 

[latest.log](https://github.com/sisby-folk/inventory-tabs/files/15366690/latest.log)
Following the log, ScreenSupport.java calls orElseThrow() and thus throws an error at line 37, because Registries.SCREEN_HANDLER.getKey(type) wasn't successful on the Screen of the Chisel, so it's again an issue with missing keys/ids from what I understand, right? :/ 

Inventory Tabs 1.3.1
Chisel Reborn 1.7.1
Minecraft 1.20.1
Fabric Loader 0.15.11
Fabric API 0.92.1

`[Render thread/ERROR]: Error executing task on Client
java.util.NoSuchElementException: No value present
	at java.util.Optional.orElseThrow(Optional.java:377) ~[?:?]
	at folk.sisby.inventory_tabs.ScreenSupport.allowTabs(ScreenSupport.java:37) ~[inventory-tabs-1.3.1+1.20.jar:?]
	at net.minecraft.class_465.handler$zon000$inventory-tabs$checkSupported(class_465.java:1206) ~[client-intermediary.jar:?]
	at net.minecraft.class_465.<init>(class_465.java:87) ~[client-intermediary.jar:?]
	at com.matthewperiut.chisel.gui.ChiselScreen.<init>(ChiselScreen.java:20) ~[chisel+fabric+1.20.1-1.7.1.jar:?]
	at net.minecraft.class_3929$class_3930.method_17543(class_3929.java:62) ~[client-intermediary.jar:?]
	at ...`

**Comment by sleepingdragoninn** [comment]
fixed in 1.3.2, missed the other possible exception in that block as you said.
